version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile.web
    ports:
      - "3005:3005"
    networks:
      - web_api_network
    depends_on:
      - db
    restart: always
    container_name: url_shorten_web
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:3005"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    labels:
      - com.host.description=web  

  api:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile.api
    ports:
      - "3004:3004"
    networks:
      - web_api_network
    depends_on:
      - db
    restart: always
    container_name: url_shorten_api
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:3004"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    labels:
      - com.host.description=api  

  db:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - web_api_network
    volumes:
      - ./data:/data
    restart: always

networks:
  web_api_network:
    driver: bridge