version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile.web
    environment:
      - DB_ADDR="db:6379"
      - DB_PASS=""
      - API_QUOTA=10
    ports:
      - "3005:3005"
    networks:
      - web_api_network
    depends_on:
      - db
    restart: always
    container_name: url_shorten_web
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:3005"]
      interval: 1m30s
      timeout: 30s
      retries: 5 

  api:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile.api
    environment:
      - DB_ADDR="db:6379"
      - DB_PASS=""
      - API_QUOTA=10
    ports:
      - "3004:3004"
    networks:
      - web_api_network
    depends_on:
      - db
    restart: always
    container_name: url_shorten_api
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:3004"]
      interval: 1m30s
      timeout: 30s
      retries: 5 

  db:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - web_api_network
    volumes:
      - ./data:/data
    restart: always
    container_name: redis-db

networks:
  web_api_network:
    driver: bridge