FROM alpine:latest

RUN adduser -S -D -H -h /webservice webuser

RUN mkdir -p /webservice

COPY ./bin/web /webservice/

COPY ./bin/.env /webservice/

RUN chmod 755 /webservice/web

RUN chown -R webuser /webservice

USER webuser

WORKDIR /webservice

EXPOSE 3005

CMD [ "./web", "-port=3005", "-env=production"]